window.portfolioProjects = [
  {
    id: "resort",
    title: "Resort",
    category: "Hospitality",
    location: "Rayong",
    role: "Interior Designer",
    status: "Design",
    year: "2024",
    scope: "Concept, 3D visualization, material mood",
    cover: "images/featured/resort-01.jpg",
    cardSize: "large",
    cardImages: ["images/featured/resort-01.jpg", "images/featured/resort-02.jpg"],
    images: ["images/featured/resort-01.jpg", "images/featured/resort-02.jpg", "images/featured/resort-bedroom-01.jpg", "images/portfolio-pages/page-03.png"],
    tags: ["Guest room", "Warm material", "Hospitality flow"],
    summary: "Resort interior design with a warm hospitality mood, soft material balance and relaxed circulation for guest experience.",
    highlight: "ออกแบบรีสอร์ตให้รู้สึกอบอุ่น พักผ่อนได้จริง และเชื่อมบรรยากาศภายในกับวิวธรรมชาติอย่างนุ่มนวล"
  },
  {
    id: "pool-villa",
    title: "Pool Villa",
    category: "Hospitality",
    location: "Concept Design",
    role: "Interior Designer",
    status: "Design",
    year: "2024",
    scope: "Pool villa mood, interior visualization, guest experience",
    cover: "images/featured/pool-villa-02.jpg",
    cardSize: "wide",
    cardImages: ["images/featured/pool-villa-02.jpg", "images/featured/pool-villa-01.jpg"],
    images: ["images/featured/pool-villa-02.jpg", "images/featured/pool-villa-01.jpg"],
    tags: ["Pool villa", "Relaxed mood", "Vacation living"],
    summary: "Pool villa design study focused on private-stay atmosphere, exterior connection and warm interior materiality.",
    highlight: "วางบรรยากาศพูลวิลล่าให้เป็นส่วนตัว โปร่งสบาย และเหมาะกับการพักผ่อนระยะสั้นแบบรีสอร์ต"
  },
  {
    id: "landscape-rmutt",
    title: "Landscape",
    category: "Education",
    location: "RMUTT",
    role: "Interior / Landscape Designer",
    status: "Design",
    year: "2023",
    scope: "Outdoor planning, visual study",
    cover: "images/portfolio-pages/page-05.png",
    images: ["images/portfolio-pages/page-05.png"],
    tags: ["Campus", "Public space", "Movement"],
    summary: "Landscape design study for public campus use, focusing on visual calm, movement and practical outdoor gathering areas.",
    highlight: "จัดพื้นที่ภายนอกให้เดินง่าย พักได้ และรองรับการใช้งานร่วมกันของนักศึกษาในชีวิตประจำวัน"
  },
  {
    id: "vip-room",
    title: "VIP Reception Room",
    category: "Workplace",
    location: "RMUTT",
    role: "Interior Designer",
    status: "Design",
    year: "2023",
    scope: "Concept, 3D visualization",
    cover: "images/featured/vip-room-01.jpg",
    cardSize: "wide",
    cardImages: ["images/featured/vip-room-01.jpg", "images/featured/vip-room-02.jpg"],
    images: ["images/featured/vip-room-01.jpg", "images/featured/vip-room-02.jpg", "images/featured/vip-room-03.jpg", "images/portfolio-pages/page-06.png"],
    tags: ["Reception", "Classic detail", "Formal seating"],
    summary: "Elegant reception room with classic wall details, chandelier lighting and formal furniture planning.",
    highlight: "ออกแบบห้องรับรอง VIP ให้ดูสุภาพ เป็นทางการ และรองรับแขกระดับผู้บริหารด้วยบรรยากาศที่น่าเชื่อถือ"
  },
  {
    id: "office-rmutt",
    title: "Office RMUTT",
    category: "Workplace",
    location: "RMUTT",
    role: "Interior Designer",
    status: "Design",
    year: "2023",
    scope: "Space planning, 3D visualization",
    cover: "images/featured/office-rmutt-01.jpg",
    cardImages: ["images/featured/office-rmutt-01.jpg", "images/featured/office-rmutt-02.jpg"],
    images: ["images/featured/office-rmutt-01.jpg", "images/featured/office-rmutt-02.jpg", "images/office/office1.png", "images/portfolio-pages/page-07.png"],
    tags: ["Office", "Marble feature", "Clean ceiling"],
    summary: "Modern office design with marble feature wall, clean ceiling detail and professional workspace planning.",
    highlight: "ออกแบบสำนักงานให้สะอาด เป็นมืออาชีพ และแบ่งพื้นที่ทำงานกับพื้นที่รับรองได้ชัดเจน"
  },
  {
    id: "office-khan",
    title: "Office K.Han",
    category: "Workplace",
    location: "Bangkok",
    role: "Interior Designer",
    status: "Design",
    year: "2024",
    scope: "Office visualization, meeting and executive work areas",
    cover: "images/featured/office-khan-01.jpg",
    cardSize: "wide",
    cardImages: ["images/featured/office-khan-01.jpg", "images/featured/office-khan-02.jpg"],
    images: ["images/featured/office-khan-01.jpg", "images/featured/office-khan-02.jpg"],
    tags: ["Private office", "Meeting", "Warm modern"],
    summary: "Private office design with warm modern material palette, composed meeting zones and polished executive atmosphere.",
    highlight: "สร้างบรรยากาศสำนักงานส่วนตัวที่อบอุ่น เรียบร้อย และเหมาะกับทั้งการทำงานและการประชุม"
  },
  {
    id: "presidents-office",
    title: "President's Office",
    category: "Workplace",
    location: "RMUTT",
    role: "Interior Designer",
    status: "Design",
    year: "2023",
    scope: "Executive office concept",
    cover: "images/portfolio-pages/page-08.png",
    images: ["images/portfolio-pages/page-08.png"],
    tags: ["Executive room", "Premium surface", "Composed mood"],
    summary: "Executive office concept with controlled contrast, premium surfaces and a composed working atmosphere.",
    highlight: "วางภาพลักษณ์ห้องผู้บริหารให้สุขุม มีน้ำหนัก และใช้วัสดุพรีเมียมอย่างพอดี"
  },
  {
    id: "gallery-art",
    title: "Gallery & Art Classroom",
    category: "Education",
    location: "RMUTT",
    role: "Interior Designer",
    status: "Renovation Design",
    year: "2024",
    scope: "Renovation, exhibition layout, lighting",
    cover: "images/featured/gallery-01.jpg",
    cardSize: "large",
    cardImages: ["images/featured/gallery-01.jpg", "images/featured/gallery-02.jpg", "images/featured/art-classroom-01.jpg"],
    images: ["images/featured/gallery-01.jpg", "images/featured/gallery-02.jpg", "images/featured/art-classroom-01.jpg", "images/project4.jpg", "images/gallery/gallery1.png"],
    tags: ["Gallery", "Classroom", "Track lighting"],
    summary: "Gallery, art classroom and hallway design with clean exhibition layout and track lighting system.",
    highlight: "ออกแบบพื้นที่แสดงงานและห้องเรียนศิลปะให้ดูโล่ง สว่าง และช่วยให้งานศิลป์เป็นจุดเด่น"
  },
  {
    id: "learning-center",
    title: "Learning Center",
    category: "Education",
    location: "Concept Design",
    role: "Interior Designer",
    status: "Concept Design",
    year: "2024",
    scope: "Concept, zoning, visual direction",
    cover: "images/portfolio-pages/page-10.png",
    images: ["images/portfolio-pages/page-10.png"],
    tags: ["Learning", "Display", "Informal meeting"],
    summary: "Learning center concept that organizes study, display and informal meeting areas into a calm educational environment.",
    highlight: "จัดพื้นที่เรียนรู้ให้เข้าใจง่าย มีมุมอ่าน มุมพูดคุย และพื้นที่แสดงข้อมูลที่ใช้งานต่อเนื่องกัน"
  },
  {
    id: "samsung-shop",
    title: "Samsung Shop",
    category: "Retail",
    location: "Concept Design",
    role: "Interior Designer",
    status: "Concept Design",
    year: "2024",
    scope: "Retail experience, display, lighting",
    cover: "images/featured/samsung-real-01.jpg",
    cardImages: ["images/featured/samsung-real-01.jpg", "images/featured/samsung-real-02.jpg", "images/featured/samsung-real-03.jpg"],
    images: ["images/featured/samsung-real-01.jpg", "images/featured/samsung-real-02.jpg", "images/featured/samsung-real-03.jpg", "images/shop/samsung0.png", "images/shop/samsung1.png", "images/shop/samsung2.png", "images/shop/samsung3.png"],
    tags: ["Retail display", "Customer flow", "Brand presence"],
    summary: "Retail experience design with product display, lighting strategy, customer flow and brand presence.",
    highlight: "ออกแบบพื้นที่ขายให้สินค้าดูเด่น ลูกค้าเดินชมได้สะดวก และสื่อภาพลักษณ์แบรนด์ได้ชัดเจน"
  },
  {
    id: "mini-shop",
    title: "Mini Shop",
    category: "Retail",
    location: "EDGE LABO",
    role: "Interior Designer",
    status: "Design & Visualization",
    year: "2025",
    scope: "Mini retail shop, counter design, display atmosphere",
    cover: "images/featured/mini-shop-01.jpg",
    cardSize: "wide",
    cardImages: ["images/featured/mini-shop-01.jpg", "images/featured/mini-shop-02.jpg", "images/featured/mini-shop-03.jpg"],
    images: ["images/featured/mini-shop-01.jpg", "images/featured/mini-shop-02.jpg", "images/featured/mini-shop-03.jpg"],
    tags: ["Mini shop", "Display", "Compact retail"],
    summary: "Compact mini shop visualization with strong storefront identity, layered display and controlled customer-facing details.",
    highlight: "ออกแบบร้านขนาดเล็กให้ใช้พื้นที่คุ้มค่า เห็นสินค้าได้ชัด และมีภาพลักษณ์หน้าร้านที่จดจำง่าย"
  },
  {
    id: "little-garden",
    title: "Little Garden",
    category: "Retail",
    location: "Concept Design",
    role: "Interior Designer",
    status: "Concept Design",
    year: "2024",
    scope: "Small shop concept",
    cover: "images/portfolio-pages/page-12.png",
    images: ["images/portfolio-pages/page-12.png"],
    tags: ["Compact shop", "Bright mood", "Garden tone"],
    summary: "Small-scale shop concept with a bright garden mood and approachable customer journey.",
    highlight: "ออกแบบร้านขนาดเล็กให้ดูสดใส เข้าถึงง่าย และใช้โทนสวนช่วยให้พื้นที่รู้สึกเป็นกันเอง"
  },
  {
    id: "hotel",
    title: "Hotel",
    category: "Hospitality",
    location: "Concept Design",
    role: "Interior Designer",
    status: "Concept Design",
    year: "2024",
    scope: "Guest room, restaurant, spa, lounge, fitness",
    cover: "images/hotel/Hotel0.jpg",
    images: ["images/hotel/Hotel0.jpg", "images/hotel/Hotel1.jpg", "images/portfolio-pages/page-13.png"],
    tags: ["Guest room", "Amenity", "Hospitality program"],
    summary: "Hospitality design including guest room, restaurant, spa, lounge and fitness area.",
    highlight: "วางงานโรงแรมให้แต่ละฟังก์ชันมีเอกลักษณ์ แต่ยังเชื่อมกันด้วยบรรยากาศที่สงบและดูพรีเมียม"
  },
  {
    id: "zen-japanese-restaurant",
    title: "Japanese / Zen Restaurant",
    category: "Hospitality",
    location: "Freelance",
    role: "Interior Designer",
    status: "Design",
    year: "2024",
    scope: "Restaurant presentation, dining atmosphere, material mood",
    cover: "images/featured/zen-restaurant-02.jpg",
    cardSize: "large",
    cardImages: ["images/featured/zen-restaurant-02.jpg", "images/featured/zen-restaurant-03.jpg", "images/featured/zen-restaurant-04.jpg"],
    images: ["images/featured/zen-restaurant-02.jpg", "images/featured/zen-restaurant-03.jpg", "images/featured/zen-restaurant-04.jpg", "images/featured/zen-restaurant-05.jpg", "images/featured/zen-restaurant-01.jpg", "images/portfolio-pages/page-14.png"],
    tags: ["Restaurant", "Japanese mood", "Dining"],
    summary: "Japanese restaurant and Zen presentation combined into one hospitality project with dining atmosphere and warm material direction.",
    highlight: "ออกแบบร้านอาหารญี่ปุ่นให้เรียบ สงบ และใช้วัสดุอบอุ่นเพื่อสร้างจังหวะการนั่งทานที่ผ่อนคลาย",
    galleryFit: true
  },
  {
    id: "one-bangkok-popup",
    title: "ONE BANGKOK Pop-up Shop",
    category: "Retail",
    location: "One Bangkok",
    role: "Interior Designer",
    status: "Design & Visualization",
    year: "2025",
    scope: "Pop-up retail visualization, counter, storefront identity",
    cover: "images/featured/one-bangkok-01.jpg",
    cardSize: "large",
    cardImages: ["images/featured/one-bangkok-01.jpg", "images/featured/waffle-sphere-01.jpg", "images/featured/popup-shop-01.jpg"],
    images: ["images/featured/one-bangkok-01.jpg", "images/featured/one-bangkok-02.jpg", "images/featured/waffle-sphere-01.jpg", "images/featured/waffle-sphere-02.jpg", "images/featured/popup-shop-01.jpg", "images/featured/popup-shop-02.jpg", "images/featured/popup-shop-03.jpg", "images/portfolio-pages/page-15.png"],
    tags: ["Pop-up", "Food retail", "One Bangkok"],
    summary: "ONE BANGKOK and pop-up shop work combined into one retail project with compact service flow and storefront identity.",
    highlight: "ออกแบบป๊อปอัปช็อปให้จดจำง่าย ใช้พื้นที่กระชับ และทำให้หน้าร้านดึงดูดสายตาในเวลาเร็ว"
  },
  {
    id: "office-sukhumvit31",
    title: "Office Sukhumvit 31",
    category: "Workplace",
    location: "Sukhumvit 31",
    role: "Interior Designer",
    status: "Design",
    year: "2025",
    scope: "Shared office, private office, reception",
    cover: "images/portfolio-pages/page-16.png",
    cardSize: "wide",
    cardImages: ["images/portfolio-pages/page-16.png", "images/portfolio-pages/page-17.png", "images/portfolio-pages/page-18.png"],
    images: ["images/portfolio-pages/page-16.png", "images/portfolio-pages/page-17.png", "images/portfolio-pages/page-18.png", "images/portfolio-pages/page-19.png"],
    tags: ["Shared office", "Meeting", "Reception"],
    summary: "Shared office and private office planning for Sukhumvit 31, balancing polished reception, meeting and work zones.",
    highlight: "จัดลำดับพื้นที่ตั้งแต่ reception ถึง private office ให้ดูเรียบร้อย ทำงานสะดวก และรองรับการประชุมได้จริง"
  },
  {
    id: "ramen-sukhumvit33",
    title: "Ramen Shop Sukhumvit 33",
    category: "Hospitality",
    location: "Sukhumvit 33",
    role: "Interior Designer",
    status: "Design",
    year: "2025",
    scope: "Restaurant planning, lighting mood",
    cover: "images/portfolio-pages/page-20.png",
    images: ["images/portfolio-pages/page-20.png"],
    tags: ["Ramen shop", "Compact planning", "Customer path"],
    summary: "Restaurant design for a ramen shop with compact planning, warm lighting and a clear customer path.",
    highlight: "ออกแบบร้านราเมนให้ใช้พื้นที่คุ้มค่า ทางเดินชัด และสร้างบรรยากาศอบอุ่นสำหรับการทานอาหารเร็ว"
  },
  {
    id: "rental-house",
    title: "Rental House",
    category: "Residential",
    location: "Entropy Architects",
    role: "Interior Designer",
    status: "Design",
    year: "2024",
    scope: "Residential interior, living area, bedroom and material mood",
    cover: "images/featured/rental-house-01.jpg",
    cardSize: "wide",
    cardImages: ["images/featured/rental-house-01.jpg", "images/featured/rental-house-02.jpg"],
    images: ["images/featured/rental-house-01.jpg", "images/featured/rental-house-02.jpg", "images/featured/rental-house-03.jpg"],
    tags: ["House", "Rental living", "Warm interior"],
    summary: "Rental house interior visualization with warm living atmosphere, practical room planning and calm residential material palette.",
    highlight: "ออกแบบบ้านเช่าให้ดูอบอุ่น ดูแลง่าย และมีฟังก์ชันที่เหมาะกับการอยู่อาศัยจริง"
  },
  {
    id: "condo-sukhumvit33",
    title: "Condo Sukhumvit 33",
    category: "Residential",
    location: "Sukhumvit 33",
    role: "Interior Designer",
    status: "Design",
    year: "2025",
    scope: "Residential interior, storage, living zones",
    cover: "images/portfolio-pages/page-21.png",
    images: ["images/portfolio-pages/page-21.png", "images/portfolio-pages/page-22.png"],
    tags: ["Condo", "Storage", "Soft modern"],
    summary: "Residential interior design with soft modern detailing and practical living zones for a Bangkok condo.",
    highlight: "เน้นพื้นที่เก็บของ การใช้งานประจำวัน และรายละเอียดที่ทำให้คอนโดเมืองดูอบอุ่นแต่ยังดูแลง่าย"
  },
  {
    id: "condo-sukhumvit24",
    title: "Condo Sukhumvit 24",
    category: "Residential",
    location: "Sukhumvit 24",
    role: "Interior Designer",
    status: "Design",
    year: "2025",
    scope: "Residential concept, compact city living",
    cover: "images/portfolio-pages/page-23.png",
    images: ["images/portfolio-pages/page-23.png"],
    tags: ["Condo", "Compact living", "Calm finishes"],
    summary: "Condo interior concept with refined storage, calm finishes and compact city-living functionality.",
    highlight: "ออกแบบคอนโดขนาดกะทัดรัดให้ใช้พื้นที่ได้คล่อง มีที่เก็บของแนบเนียน และบรรยากาศสงบ"
  },
  {
    id: "aluminium-profile",
    title: "Aluminum Profile",
    category: "Visualization",
    location: "Car Shop / Furniture",
    role: "Interior Designer",
    status: "Design & Visualization",
    year: "2025",
    scope: "Furniture visualization, material study",
    cover: "images/portfolio-pages/page-24.png",
    images: ["images/portfolio-pages/page-24.png", "images/portfolio-pages/page-27.png"],
    tags: ["Furniture", "Aluminum profile", "Material detail"],
    summary: "Aluminum profile furniture and retail visualization with detailed product expression and material-focused renderings.",
    highlight: "พัฒนาเฟอร์นิเจอร์และงาน display จาก aluminum profile ให้เห็นเส้นสาย วัสดุ และรายละเอียดการประกอบชัดเจน"
  },
  {
    id: "ai-render",
    title: "AI Render",
    category: "Visualization",
    location: "Raminthra",
    role: "Interior Designer",
    status: "AI Visualization",
    year: "2025",
    scope: "AI-assisted atmosphere study",
    cover: "images/portfolio-pages/page-25.png",
    images: ["images/portfolio-pages/page-25.png"],
    tags: ["AI render", "Airbnb", "Mood study"],
    summary: "AI-assisted rendering study for Airbnb and interior atmosphere exploration.",
    highlight: "ใช้ AI ช่วยสำรวจ mood ของพื้นที่อย่างรวดเร็ว เพื่อหาแนวทางภาพรวมก่อนพัฒนาแบบละเอียด"
  },
  {
    id: "logo-design",
    title: "Logo Design",
    category: "Visualization",
    location: "Concept",
    role: "Designer",
    status: "Graphic Design",
    year: "2025",
    scope: "Visual identity exploration",
    cover: "images/portfolio-pages/page-26.png",
    images: ["images/portfolio-pages/page-26.png"],
    tags: ["Logo", "Identity", "Presentation"],
    summary: "Logo exploration and visual identity work for brand presentation.",
    highlight: "ออกแบบโลโก้และภาพลักษณ์ให้จดจำง่าย ใช้ต่อในงานนำเสนอและการสื่อสารแบรนด์ได้ชัดเจน",
    galleryFit: true
  }
];
